## Welcome to the <u>Day 14</u> of "40 Days of JavaScript!"

#### Note

## 1. Different Types of Error in JavaScript

| Error Type     | ржХржЦржи рж╣ржпрж╝                              |
| -------------- | --------------------------------      |
| SyntaxError    | ржХрзЛржб рж▓рзЗржЦрж╛рж░ ржирж┐ржпрж╝ржо ржнрж╛ржЩрж▓рзЗ                |
| ReferenceError | ржЕржШрзЛрж╖рж┐ржд ржнрзНржпрж╛рж░рж┐ржпрж╝рзЗржмрж▓ ржмрзНржпржмрж╣рж╛рж░ ржХрж░рж▓рзЗ         |
| TypeError      | ржнрзБрж▓ ржЯрж╛ржЗржкрзЗрж░ ржнрзНржпрж╛рж▓рзБрждрзЗ ржЕржкрж╛рж░рзЗрж╢ржи ржХрж░рж▓рзЗ      |
| RangeError     | ржнрзНржпрж╛рж▓рзБ рж░рзЗржЮрзНржЬрзЗрж░ ржмрж╛ржЗрж░рзЗ ржЧрзЗрж▓рзЗ                 |
| EvalError      | eval() ржмрзНржпржмрж╣рж╛рж░ рж╕ржВржХрзНрж░рж╛ржирзНржд рж╕ржорж╕рзНржпрж╛            |
| URIError       | URI encode/decode ржнрзБрж▓ ржЗржиржкрзБржЯ ржжрж┐рж▓рзЗ      |


### 1. SyntaxError
ржХржЦржи рж╣ржпрж╝?
ржпржЦржи ржХрзЛржбрзЗ ржХрзЛржи syntax ржнрзБрж▓ ржерж╛ржХрзЗред

ржЙржжрж╛рж╣рж░ржг:

        if (true {
        console.log("Hello");
        }

ЁЯФ┤ Output: SyntaxError: Unexpected token ')'

### 2. ReferenceError
ЁЯУМ ржХржЦржи рж╣ржпрж╝?

ржпржЦржи ржПржоржи ржХрзЛржи ржнрзНржпрж╛рж░рж┐ржпрж╝рзЗржмрж▓ ржмрж╛ ржлрж╛ржВрж╢ржи ржХрж▓ ржХрж░рж╛ рж╣ржпрж╝ ржпрзЗржЯрж╛ ржбрж┐ржХрзНрж▓рзЗрзЯрж╛рж░ ржХрж░рж╛ рж╣рзЯржирж┐ред

ржЙржжрж╛рж╣рж░ржг:

        console.log(x); // x ржбрж┐ржХрзНрж▓рзЗрзЯрж╛рж░ ржХрж░рж╛ рж╣рзЯржирж┐

ЁЯФ┤ Output: ReferenceError: x is not defined

### 3. TypeError
ЁЯУМ ржХржЦржи рж╣ржпрж╝?

ржпржЦржи ржнрзБрж▓ ржЯрж╛ржЗржкрзЗрж░ ржнрзНржпрж╛рж▓рзБрждрзЗ ржЕржкрж╛рж░рзЗрж╢ржи ржХрж░рж╛рж░ ржЪрзЗрж╖рзНржЯрж╛ ржХрж░рж╛ рж╣ржпрж╝ред

ржЙржжрж╛рж╣рж░ржг:

        let num = 5;
        num.toUpperCase(); // рж╕ржВржЦрзНржпрж╛ ржерзЗржХрзЗ uppercase?

ЁЯФ┤ Output: TypeError: num.toUpperCase is not a function

ржЙржжрж╛рж╣рж░ржг 2:

        let obj = null;
        console.log(obj.name); // TypeError: Cannot read properties of null


### 4. RangeError
ЁЯУМ ржХржЦржи рж╣ржпрж╝?

ржпржЦржи ржХрзЛржирзЛ ржнрзНржпрж╛рж▓рзБ ржЧрзНрж░рж╣ржгржпрзЛржЧрзНржп рж░рзЗржЮрзНржЬрзЗрж░ ржмрж╛ржЗрж░рзЗ ржЪрж▓рзЗ ржпрж╛ржпрж╝ред

ржЙржжрж╛рж╣рж░ржг:

        let arr = new Array(-1) // RangeError 
        
        // Array-ржПрж░ рж╕рж╛ржЗржЬ ржирзЗржЧрзЗржЯрж┐ржн рж╣рждрзЗ ржкрж╛рж░рзЗ ржирж╛

ЁЯФ┤ Output: RangeError: Invalid array length

### 5. EvalError
ЁЯУМ ржХржЦржи рж╣ржпрж╝?

eval() ржлрж╛ржВрж╢ржи ржмрзНржпржмрж╣рж╛рж░ ржХрж░рж╛рж░ рж╕ржоржпрж╝ ржнрзБрж▓ ржХрж┐ржЫрзБ ржХрж░рж▓рзЗред

        eval("var a = ;"); // EvalError

тЭЧ ржПржЗ error ржПржЦржи ржЦрзБржм ржХржо ржжрзЗржЦрж╛ ржпрж╛ржпрж╝, ржмрж┐рж╢рзЗрж╖ ржкрж░рж┐рж╕рзНржерж┐рждрж┐рждрзЗ рж╢рзБржзрзБ ржЖрж╕рзЗред

### 6. URIError
ЁЯУМ ржХржЦржи рж╣ржпрж╝?

decodeURI() ржмрж╛ encodeURI() ржПрж░ рж╕рж╛ржерзЗ ржнрзБрж▓ ржЗржиржкрзБржЯ ржжрж┐рж▓рзЗред

ржЙржжрж╛рж╣рж░ржг:

        decodeURIComponent("%"); // URIError

ЁЯФ┤ Output: URIError: URI malformed


### тЪая╕П Parsing Error (Syntax Error)
ржПржЯрж╛ ржЖрж╕рж▓рзЗ syntax error-ржПрж░ ржПржХржЯрж┐ ржзрж░ржи, ржпрж╛ JavaScript ржЗржЮрзНржЬрж┐ржи ржХрзЛржб parse ржХрж░рж╛рж░ рж╕ржоржпрж╝ ржЦрзБржБржЬрзЗ ржкрж╛ржпрж╝ред

ржЕрж░рзНржерж╛рзО, JavaScript ржпржЦржи ржХрзЛржбрзЗрж░ рж╕рзНржЯрзНрж░рж╛ржХржЪрж╛рж░ ржмрж┐рж╢рзНрж▓рзЗрж╖ржг ржХрж░рзЗ, рждржЦржи ржпржжрж┐ syntax ржнрзБрж▓ ржерж╛ржХрзЗ тАФ рждржЦржи parsing error ржШржЯрзЗред

тЬЕ ржХржЦржи рж╣ржпрж╝?

ржнрзБрж▓ ржмрзНрж░рзНржпрж╛ржХрзЗржЯ

ржнрзБрж▓ржнрж╛ржмрзЗ if, for ржЗрждрзНржпрж╛ржжрж┐ рж▓рзЗржЦрж╛

ржнрзБрж▓ рж╕рзЗржорж┐ржХрзЛрж▓ржи ржмрж╛ ржХрзЛрж▓ржи

ЁЯОп ржЙржжрж╛рж╣рж░ржг:

        function sayHello( {
        console.log("Hello");
        }
    // SyntaxError: Unexpected token '{'

ржмрзНржпрж╛ржЦрзНржпрж╛: ржУржкрж░рзЗ ржлрж╛ржВрж╢ржирзЗрж░ ржмрзНрж░рзНржпрж╛ржХрзЗржЯ ржЧржаржи ржнрзБрж▓, рждрж╛ржЗ JavaScript ржХрзЛржб "parse" ржХрж░рждрзЗ ржкрж╛рж░рзЗржирж┐ тАФ ржПржЯрж┐ parsing errorред

### тЪая╕П Runtime Error
ржПржЗ error ржХрзЛржб рж╕ржарж┐ржХржнрж╛ржмрзЗ ржкрж╛рж░рзНрж╕ рж╣ржпрж╝, ржХрж┐ржирзНрждрзБ ржпржЦржи ржХрзЛржб ржЪрж╛рж▓рж╛ржирзЛ рж╣ржпрж╝ (run time) рждржЦржи рж╕ржорж╕рзНржпрж╛ ржжрзЗржЦрж╛ ржжрзЗржпрж╝ред

тЬЕ ржХржЦржи рж╣ржпрж╝?

ржЕржШрзЛрж╖рж┐ржд ржнрзНржпрж╛рж░рж┐ржпрж╝рзЗржмрж▓ ржмрзНржпржмрж╣рж╛рж░

null ржмрж╛ undefined ржерзЗржХрзЗ ржкрзНрж░ржкрж╛рж░рзНржЯрж┐ ржкржбрж╝рж╛

ржнрзБрж▓ ржЯрж╛ржЗржкрзЗ ржЕржкрж╛рж░рзЗрж╢ржи ржХрж░рж╛

ЁЯОп ржЙржжрж╛рж╣рж░ржг: 

        let user;
        console.log(user.name); // user рж╣рж▓рзЛ undefined

        TypeError: Cannot read property 'name' of undefined
ржмрзНржпрж╛ржЦрзНржпрж╛: ржХрзЛржб рж╕рж┐ржиржЯрзНржпрж╛ржХрзНрж╕ ржарж┐ржХ ржЖржЫрзЗ, рждрж╛ржЗ parse рж╣ржпрж╝рзЗржЫрзЗред ржХрж┐ржирзНрждрзБ ржЪрж╛рж▓рж╛ржирзЛрж░ рж╕ржоржпрж╝ user undefined, рждрж╛ржЗ error ржПрж╕рзЗржЫрзЗ тАФ ржПржЯрж┐ runtime errorред


## 2. Handling Errors With try and catch

### try...catch ржХрж┐?
try...catch рж╣ржЪрзНржЫрзЗ JavaScript-ржПрж░ ржПржХржЯрж┐ error-handling structure, ржпрзЗржЯрж╛ ржХрзЛржбрзЗ ржХрзЛржирзЛ error рж╣рж▓рзЗ рж╕рзЗржЯрж╛ ржзрж░рждрзЗ ржПржмржВ ржкрзНрж░рзЛржЧрзНрж░рж╛ржо ржмржирзНржз ржирж╛ ржХрж░рзЗ рж╕рзЗржЗ error рж╣рзНржпрж╛ржирзНржбрзЗрж▓ ржХрж░рждрзЗ рж╕рж╛рж╣рж╛ржпрзНржп ржХрж░рзЗред

Basic Syntax:

        try {
             // logic or code
            // ржПржЦрж╛ржирзЗ  рж╕рзЗржЗ ржХрзЛржб рж▓рж┐ржЦрзЛ ржпрзЗржЯрж╛рждрзЗ error рж╣рждрзЗ ржкрж╛рж░рзЗ
        } catch (error) {
            // handle error
            // ржпржжрж┐ try ржмрзНрж▓ржХрзЗ error рж╣рзЯ, рждрж╛рж╣рж▓рзЗ ржПржЦрж╛ржирзЗ ржПрж╕рзЗ error ржзрж░ржмрзЗ
        }

### ЁЯзн Flow (ржкрзНрж░ржмрж╛рж╣):

    1. Code inside try gets executed.
    2. If no error in the try block, the catch block will be ignored and will not be
    executed.
    3. If there is an error in the try block, the execution of the try block will be
    suspended and the control will move to the catch block. In the catch block you
    can find the error details and do the needful.

ЁЯСЙ ржкрзНрж░ржержорзЗ try ржмрзНрж▓ржХ execute рж╣ржпрж╝ред

ЁЯСЙ ржпржжрж┐ try ржмрзНрж▓ржХрзЗ error ржирж╛ ржерж╛ржХрзЗ, рждрж╛рж╣рж▓рзЗ catch ржмрзНрж▓ржХрзЗ ржпрж╛ржУрзЯрж╛ рж╣ржмрзЗ ржирж╛ред

ЁЯСЙ ржпржжрж┐ try ржмрзНрж▓ржХрзЗ error ржерж╛ржХрзЗ, рждржЦржи catch ржмрзНрж▓ржХрзЗ рж▓рж╛ржл ржжрзЗрзЯ ржПржмржВ error object ржкрж╛ржарж╛рзЯред

тЪая╕П ржПрж░ ржлрж▓рзЗ ржкрзНрж░рзЛржЧрзНрж░рж╛ржо ржХрзНрж░рзНржпрж╛рж╢ ржХрж░рзЗ ржирж╛, ржмрж░ржВ рж╕рзБржирзНржжрж░ржнрж╛ржмрзЗ ржЪрж╛рж▓рзБ ржерж╛ржХрзЗред

        try {
            console.log("execution starts here");
            abc;
            console.log("execution ends here");
        } catch (err) {
            console.error("An Error has occured");

            console.log(err.name)
            console.log(err.message)
            console.log(err.stack)
        }

Another Example

        try {
            let result = 10 / 0;
            console.log(user); // user is not defined
        } catch (err) {
            console.log("An Error has occured:", err.message);
        }

ЁЯФ╡ Output: An Error has occured: user is not defined

### Error Object (err)
catch(err)-ржП ржпрзЗржЯрж╛ ржкрзНржпрж╛рж░рж╛ржорж┐ржЯрж╛рж░ рж╣рж┐рж╕рзЗржмрзЗ ржкрж╛ржЗ, рж╕рзЗржЯрж╛ ржПржХржЯрж╛ Error objectред

ржПржЯрж╛рж░ ржорж╛ржзрзНржпржорзЗ  error рж╕ржорзНржкрж░рзНржХрзЗ ржЕржирзЗржХ ржХрж┐ржЫрзБ ржЬрж╛ржирждрзЗ ржкрж╛рж░:

    err.name тАУ error ржПрж░ ржирж╛ржо (ржпрзЗржоржи: ReferenceError)

    err.message тАУ error message

    err.stack тАУ ржХрзЛржерж╛ ржерзЗржХрзЗ error ржПрж╕рзЗржЫрзЗ (debugging-ржП ржХрж╛ржЬрзЗ рж▓рж╛ржЧрзЗ)


| Part          | ржХрж╛ржЬ                                    |
| ------------- | -------------------------------------- |
| `try`         | рж╕ржирзНржжрзЗрж╣ржЬржиржХ ржХрзЛржб ржмрзНрж▓ржХ                     |
| `catch(err)`  | ржпржжрж┐ error рж╣рзЯ, рждрж╛рж╣рж▓рзЗ ржПржЦрж╛ржирзЗ рж╣рзНржпрж╛ржирзНржбрзЗрж▓ рж╣рзЯ |
| `err.message` | error ржПрж░ ржорзЗрж╕рзЗржЬ ржжрзЗржЦрж╛рзЯ                   |


## 3. ржмрж╛рж╕рзНрждржм ржЬрзАржмржирзЗрж░ ржмрзНржпржмрж╣рж╛рж░ (Real-World Use Cases)

### 1. API Call (Fetch Request)
ржпржЦржи ржЖржорж░рж╛ рж╕рж╛рж░рзНржнрж╛рж░ ржерзЗржХрзЗ ржбрзЗржЯрж╛ ржЖржирж┐ (ржпрзЗржоржи: REST API), рждржЦржи ржЗржирзНржЯрж╛рж░ржирзЗржЯ рж╕ржорж╕рзНржпрж╛ ржмрж╛ рж╕рж╛рж░рзНржнрж╛рж░ ржбрж╛ржЙржи ржерж╛ржХрж▓рзЗ error рж╣рждрзЗ ржкрж╛рж░рзЗред рждрж╛ржЗ try...catch ржмрзНржпржмрж╣рж╛рж░ ржХрж░рж┐ред

        async function getUserData() {
        try {
            const res = await fetch('https://jsonplaceholder.typicode.com/users/1');
            const data = await res.json();
            console.log(data);
        } catch (err) {
            console.log('тЪая╕П ржЗржЙржЬрж╛рж░ ржбрзЗржЯрж╛ ржЖржирждрзЗ рж╕ржорж╕рзНржпрж╛ рж╣рзЯрзЗржЫрзЗ:', err.message);
        }
        }
        getUserData();

### 2. Form Validation
ржЗржЙржЬрж╛рж░ ржнрзБрж▓ ржЗржиржкрзБржЯ ржжрж┐рж▓рзЗ error ржзрж░рж╛рж░ ржЬржирзНржп try...catch ржмрзНржпржмрж╣рж╛рж░ ржХрж░рж╛ ржпрж╛рзЯред

        function submitForm(user) {
        try {
            if (!user.name) {
            throw new Error("ржирж╛ржо ржЕржмрж╢рзНржпржЗ ржжрж┐рждрзЗ рж╣ржмрзЗ!");
            }
            console.log("Form submitted:", user);
        } catch (err) {
            console.log("тЭМ ржлрж░рзНржо рж╕ржорж╕рзНржпрж╛:", err.message);
        }
        }
        submitForm({}); // ржирж╛ржо ржирзЗржЗ


### 3. LocalStorage ржмрзНржпржмрж╣рж╛рж░ ржХрж░рж╛рж░ рж╕ржорзЯ
рж╕ржм ржмрзНрж░рж╛ржЙржЬрж╛рж░ localStorage рж╕рж╛ржкрзЛрж░рзНржЯ ржХрж░рзЗ ржирж╛ ржмрж╛ user ржпржжрж┐ privacy mode ржП ржерж╛ржХрзЗ, рждржЦржи error рж╣рждрзЗ ржкрж╛рж░рзЗред

        try {
        localStorage.setItem('theme', 'dark');
        } catch (err) {
        console.log("тЪая╕П LocalStorage ржХрж╛ржЬ ржХрж░ржЫрзЗ ржирж╛:", err.message);
        }

### 4. JSON.parse() ржХрж░рж╛рж░ рж╕ржорзЯ
ржпржЦржи ржбрзЗржЯрж╛ parse ржХрж░рждрзЗ рж╣рзЯ, ржХрж┐ржирзНрждрзБ рж╕рзЗржЯрж╛ invalid JSON рж╣рж▓рзЗ error рж╣рзЯред

        const jsonString = '{"name":"Masum", "age":25}'; // ржарж┐ржХ ржЖржЫрзЗ

        try {
        const data = JSON.parse(jsonString);
        console.log(data.name);
        } catch (err) {
        console.log("тЭМ JSON ржкрж╛рж░рзНрж╕ ржХрж░рж╛ ржпрж╛рзЯржирж┐:", err.message);
        }

тЬ│я╕П ржпржжрж┐ JSON ржнрзБрж▓ рж╣рждрзЛ (ржпрзЗржоржи "{name:Masum}"), рждрж╛рж╣рж▓рзЗ catch ржмрзНрж▓ржХрзЗ ржЪрж▓рзЗ ржпрзЗрждред

### 5. Third-Party Library Error Handling
рждрзБржорж┐ ржпржжрж┐ ржЕржирзНржп ржХрзЛржирзЛ рж▓рж╛ржЗржмрзНрж░рзЗрж░рж┐ ржмрж╛ ржХрзЛржб ржмрзНржпржмрж╣рж╛рж░ ржХрж░рзЛ (ржпрзЗржЯрж╛ рждрзБржорж┐ ржирж┐ржЬрзЗ рж▓рж┐ржЦрзЛ ржирж┐), рж╕рзЗржЦрж╛ржирзЗ ржнрзБрж▓ рж╣рж▓рзЗ try...catch ржжрж┐рзЯрзЗ рждрж╛ржХрзЗ ржирж┐рзЯржирзНрждрзНрж░ржгрзЗ рж░рж╛ржЦрж╛ ржпрж╛рзЯред

        try {
        someExternalFunction(); // ржпржжрж┐ ржПржЗ ржлрж╛ржВрж╢ржирзЗ рж╕ржорж╕рзНржпрж╛ ржерж╛ржХрзЗ
        } catch (err) {
        console.log("тЪая╕П ржмрж╛ржЗрж░рзЗрж░ ржлрж╛ржВрж╢ржирзЗ рж╕ржорж╕рзНржпрж╛:", err.message);
        }



## 4. Throwing Error

### What is throw?
ЁЯСЙ throw keyword ржмрзНржпржмрж╣рж╛рж░ ржХрж░рзЗ рждрзБржорж┐ ржирж┐ржЬрзЗрж░ ржорждрзЛ ржХрж░рзЗ ржПржХржЯрж┐ error рждрзИрж░рж┐ ржХрж░рждрзЗ ржкрж╛рж░рзЛ ржПржмржВ рж╕рзЗржЯрж┐ "throw" ржмрж╛ ржЫрзБржБрзЬрзЗ ржжрж┐рждрзЗ ржкрж╛рж░рзЛред

ЁЯФ┤ ржПржЯрж┐ рж╕рж╛ржзрж╛рж░ржгржд рждржЦржи ржмрзНржпржмрж╣рж╛рж░ рж╣рзЯ, ржпржЦржи рждрзБржорж┐ ржХрж┐ржЫрзБ ржЪрзЗржХ ржХрж░рзЗ ржжрзЗржЦрзЛ тАФ ржПржмржВ ржнрзБрж▓ рж╣рж▓рзЗ ржЗржЪрзНржЫрж╛ ржХрж░рзЗ error рждрзИрж░рж┐ ржХрж░рзЛред

ЁЯза Syntax:

        throw new Error("Own Custom error message");

##### Example

        function validateAge(age) {
            try {
                if (isNaN(age)) {
                    throw new Error(`Invalid input: Age must be a number. Your input is ${age}`);
                }
                console.log(`User's age is: ${age}`);
            } catch (error) {
                console.error("Validation Error:", error.message);
            }
        }

         validateAge("Tapas") // Invalid input: Age must be a number. Your input is Tapas


##### ЁЯОп Example: Input Validation

        function divide(a, b) {
        if (b === 0) {
            throw new Error("тЭМ 0 ржжрж┐рзЯрзЗ ржнрж╛ржЧ ржХрж░рж╛ ржпрж╛рзЯ ржирж╛!");
        }
        return a / b;
        }

        try {
        console.log(divide(10, 0));
        } catch (err) {
        console.log("тЪая╕П рж╕ржорж╕рзНржпрж╛:", err.message);
        }


ЁЯЯв Output: тЪая╕П рж╕ржорж╕рзНржпрж╛: тЭМ 0 ржжрж┐рзЯрзЗ ржнрж╛ржЧ ржХрж░рж╛ ржпрж╛рзЯ ржирж╛!

## 5. Rethrowing Error ржорж╛ржирзЗ ржХрзА?
Rethrow ржорж╛ржирзЗ рж╣рж▓рзЛ:

    catch ржмрзНрж▓ржХрзЗ error ржзрж░рж╛рж░ ржкрж░, рждрзБржорж┐ ржЪрж╛ржЗрж▓рзЗржЗ ржЖржмрж╛рж░ рж╕рзЗржЗ error-ржЯрж┐ ржкрзБржирж░рж╛рзЯ ржЫрзБржБрзЬрзЗ (throw) ржжрж┐рждрзЗ ржкрж╛рж░рзЛ тАФ ржпрзЗржи ржкрж░ржмрж░рзНрждрзАрждрзЗ ржЖрж░рзЗржХ ржЬрж╛рзЯржЧрж╛рзЯ рж╕рзЗржЯрж╛ ржзрж░рж╛ ржмрж╛ рж╣рзНржпрж╛ржирзНржбрзЗрж▓ ржХрж░рж╛ ржпрж╛рзЯред

### ЁЯУМ ржХрзЗржи ржмрзНржпржмрж╣рж╛рж░ ржХрж░ржм?
ржХржЦржирзЛ ржХржЦржирзЛ рждрзБржорж┐ рж╕ржм error catch ржмрзНрж▓ржХрзЗ рж╣рзНржпрж╛ржирзНржбрзЗрж▓ ржХрж░рждрзЗ ржЪрж╛ржУ ржирж╛ред

ржХрж┐ржЫрзБ error рж╢рзБржзрзБ рж▓ржЧ ржХрж░рзЗ, ржЖржмрж╛рж░ ржЫрзБржБрзЬрзЗ ржжрж┐рждрзЗ ржЪрж╛ржУ тАФ ржпрзЗржи ржЙржкрж░рзЗрж░ рж▓рзЗржнрзЗрж▓рзЗ рж╣рзНржпрж╛ржирзНржбрзЗрж▓ ржХрж░рж╛ ржпрж╛рзЯред

#### ЁЯза Structure:

        try {
        // ржХрзЛржб
        } catch (err) {
        if (err.message === "рж╕рж╛ржзрж╛рж░ржг рж╕ржорж╕рзНржпрж╛") {
            console.log("тЫФ рж╣рзНржпрж╛ржирзНржбрзЗрж▓ ржХрж░рж╛ рж╣рж▓рзЛ:", err.message);
        } else {
            throw err; // ржЖржмрж╛рж░ ржЫрзБржБрзЬрзЗ ржжрж╛ржУ
        }
        }


 Example: Rethrowing Erro

        function validateForm(formData) {
            try {
                if (!formData.username) throw new Error("Username is Mandatory");
                if (!formData.email.includes("@")) throw new Error("Invalid email format!");
            } catch (error) {
                console.error("Validation Issues Found:", error.message);
            } else {
                throw error; // rethrow // ржЕржирзНржп ржпрзЗржХрзЛржирзЛ error ржЖржмрж╛рж░ ржЫрзБржБрзЬрзЗ ржжрж╛ржУ
            }
        }

        try {
            validateForm({ username: "Tapas", email: "bademail" }) // // Invalid email
        } catch(error) {
            console.error("Showing error message for user creation", error.message)
        }

ЁЯФ┤  Output: Showing error message for user creation Invalid email format!

ржЖрж░ ржпржжрж┐ ржЕржирзНржп error ржерж╛ржХржд, рждрж╛рж╣рж▓рзЗ рж╕рзЗржЯрж╛ catch ржерзЗржХрзЗ ржЖржмрж╛рж░ throw рж╣рзЯрзЗ ржЙржкрж░рзЗрж░ рж▓рзЗржнрзЗрж▓рзЗ ржзрж░рж╛ ржпрзЗрждред


## 6. try-catch-finally ржХрзА?
JavaScript-ржП error handle ржХрж░рж╛рж░ рж╕ржорзЯ ржЖржорж░рж╛ try ржПржмржВ catch ржПрж░ рж╕рж╛ржерзЗ finally ржмрзНржпржмрж╣рж╛рж░ ржХрж░рждрзЗ ржкрж╛рж░рж┐ред
finally block рж╕ржмрж╕ржорзЯ ржЪрж▓рзЗ, error рж╣рзЛржХ ржмрж╛ ржирж╛ рж╣рзЛржХред

ЁЯз▒ Basic Structure:

        try {
            // ржХрзЛржб ржпрж╛ error ржХрж░рждрзЗ ржкрж╛рж░рзЗ
        } catch (err) {
            // error ржзрж░рж╛рж░ ржЬрж╛рзЯржЧрж╛
        } finally {
            // рж╕ржмрж╢рзЗрж╖рзЗ ржпрж╛-ржЗ рж╣рзЛржХ, ржПржЗ ржХрзЛржб ржЪрж▓ржмрзЗржЗ
            // Code that always runs (cleanup actions)
        }

ЁЯОп ржЙржжрж╛рж╣рж░ржг рзз: No Error

        try {
        console.log("ЁЯУе ржбрзЗржЯрж╛ ржкрзНрж░рж╕рзЗрж╕ рж╣ржЪрзНржЫрзЗ...");
        let result = 10 / 2;
        console.log("тЬЕ ржлрж▓рж╛ржлрж▓:", result);
        } catch (err) {
        console.log("тЭМ Error:", err.message);
        } finally {
        console.log("ЁЯФЪ ржПржЗ ржЕржВрж╢ рж╕ржмрж╕ржорзЯ ржЪрж▓ржмрзЗ!");
        }

ЁЯЯв Output: 

            ЁЯУе ржбрзЗржЯрж╛ ржкрзНрж░рж╕рзЗрж╕ рж╣ржЪрзНржЫрзЗ...
            тЬЕ ржлрж▓рж╛ржлрж▓: 5
            ЁЯФЪ ржПржЗ ржЕржВрж╢ рж╕ржмрж╕ржорзЯ ржЪрж▓ржмрзЗ!


ЁЯОп ржЙржжрж╛рж╣рж░ржг рзи: Error ржерж╛ржХрж▓рзЗржУ finally ржЪрж▓рзЗ

        try {
        let x = y + 1; // y is not defined (ReferenceError)
        } catch (err) {
        console.log("тЭМ ржзрж░рж╛ ржкрзЬрж▓рзЛ:", err.message);
        } finally {
        console.log("ЁЯФЪ ржлрж╛ржЗржирж╛рж▓рж┐ ржмрзНрж▓ржХ рж╕ржмрж╕ржорзЯ ржЪрж▓ржмрзЗ!");
        }

ЁЯЯв Output:  

        тЭМ ржзрж░рж╛ ржкрзЬрж▓рзЛ: y is not defined
        ЁЯФЪ ржлрж╛ржЗржирж╛рж▓рж┐ ржмрзНрж▓ржХ рж╕ржмрж╕ржорзЯ ржЪрж▓ржмрзЗ!

##### ржмрж╛рж╕рзНрждржм ржЬрзАржмржирзЗ ржХрзЛржерж╛рзЯ finally ржжрж░ржХрж╛рж░ рж╣рзЯ?

| Use Case                      | ржЙржжрж╛рж╣рж░ржг                          |
| ----------------------------- | ------------------------------- |
| тЬЕ Cleanup                     | File ржмрж╛ Connection ржмржирзНржз ржХрж░рж╛     |
| ЁЯз╣ Loading Indicator ржмржирзНржз ржХрж░рж╛ | UI ржерзЗржХрзЗ рж▓рзЛржбрж┐ржВ рж░рж┐ржорзБржн ржХрж░рж╛         |
| тП▒я╕П Timer ржмржирзНржз ржХрж░рж╛             | API response ржжрзЗрж░рж┐ ржХрж░рж▓рзЗ рж╕рзНржЯржк ржХрж░рж╛ |


## 7. Creating Custom Error

#### Custom Error ржорж╛ржирзЗ ржХрзА?
JavaScript-ржП ржЖржорж░рж╛ ржЪрж╛ржЗрж▓рзЗ ржирж┐ржЬрзЗрж░ ржорждрзЛ ржХрж░рзЗ ржирждрзБржи Error ржЯрж╛ржЗржк рждрзИрж░рж┐ ржХрж░рждрзЗ ржкрж╛рж░рж┐ред

ржПржЧрзБрж▓рзЛржХрзЗ ржмрж▓рзЗ ЁЯСЙ Custom Errorsред

тЮбя╕П ржПржЧрзБрж▓рзЛ рж╕рж╛ржзрж╛рж░ржгржд Error class extend ржХрж░рзЗ рждрзИрж░рж┐ ржХрж░рж╛ рж╣рзЯред

#### ЁЯФз ржХрзЗржи Custom Error ржжрж░ржХрж╛рж░?
ржирж┐рж░рзНржжрж┐рж╖рзНржЯ ржнрзБрж▓рзЗрж░ ржЬржирзНржп ржЖрж▓рж╛ржжрж╛ error рждрзИрж░рж┐ ржХрж░рж╛ ржпрж╛рзЯред

Debug ржмрж╛ logging рж╕рж╣ржЬ рж╣рзЯред

ржмрзЬ ржЕрзНржпрж╛ржкрзЗ ржмрж┐ржнрж┐ржирзНржи error ржЖрж▓рж╛ржжрж╛ ржЖрж▓рж╛ржжрж╛ рж╣рзНржпрж╛ржирзНржбрзЗрж▓ ржХрж░рж╛ ржпрж╛рзЯред

ЁЯза Basic Syntax:

        class MyCustomError extends Error {
        constructor(message) {
            super(message);        // parent class-ржПрж░ constructor ржХрж▓
            this.name = "MyCustomError";  // ржХрж╛рж╕рзНржЯржо ржирж╛ржо
            }
        }

ЁЯОп Example: Constructor Function ржжрж┐рзЯрзЗ Custom Error

        function ValidationError(message) {
            this.name = "ValidationError";
            this.message = message;
            this.stack = (new Error()).stack; // error trace
        }

        // Error ржПрж░ prototype ржЗржирж╣рзЗрж░рж┐ржЯ ржХрж░рж╛ржирзЛ
        ValidationError.prototype = Object.create(Error.prototype);
        ValidationError.prototype.constructor = ValidationError;

        function validateCitizen(age) {
        if (age < 60) {
            throw new ValidationError("You are not a senior citizen");
        }
        return "You are a senior citizen";
        }

        try {
            const message = validateCitizen(15);
            console.log(message);
        } catch (error) {
            console.error(`${error.name}: ${error.message}`);
        }


ЁЯЯв Output:

        ValidationError: You are not a senior citizen

ржПржЦржи ValidationError ржкрзБрж░рзЛржкрзБрж░рж┐ Error ржПрж░ ржорждрзЛржЗ behave ржХрж░ржмрзЗред
